### ISSUE TITLE
这个代码库是server端的还是client端的

### ISSUE THREAD

**Issue by wonleing** [PingPlusPlus/pingpp-js#1]
我之前用的python版的pingserver (有一些自己的改动)，html-one的客户端。
貌似用不到更新这个代码库里的东西吧？

**Comment by wonleing** [comment]
现在老的壹收款是被完全放弃掉了吗？新注册的号都用这套client的代码了吗？
和老版壹收款相比变化也太大了，完全不知道怎么迁移过来，有没有在老代码上进行些小改动能用的方法

**Comment by samurai00** [comment]
这个是客户端的。是原来的不包含 壹收款 的 SDK。壹收款，目前还没有添加到这里。

**Comment by wonleing** [comment]
如果我想继续在新接口商户中使用壹收款 应该如何更新

**Comment by samurai00** [comment]
壹收款还是原来的那个地址，没有变的。现在是用着遇到什么问题了吗？

**Comment by wonleing** [comment]
在pingxx上新注册的帐号商户不能使用支付宝付款，总是提示请求参数错误，service不合法。
另外壹收款在github上的地址是什么？想看看最近有什么更新，却怎么也找不到了。

**Comment by wonleing** [comment]
不能使用的原因我也是知道的，因为SDK更新了。不过官网SDK升级文档里提到的SDK在壹收款中并没有使用到，应该并不适用于壹收款。壹收款里使用的是pingpp_one.js pay.htm ap.js. 这些文件在新SDK中并没有。能不能直接在https://github.com/PingPlusPlus/pingpp-html5/tree/one这个项目里进行一下代码更新呢？
