### ISSUE TITLE
有计划支持微信小程序内支付吗？

### ISSUE THREAD

**Issue by superborges** [PingPlusPlus/pingpp-js#13]
微信小程序支付，好像也是调用的微信公众号支付，有计划支持吗？

**Comment by dong11** [comment]
微信小程序只支持微信渠道支付，并不支持其他渠道，你要做的话只需要取出charge中的字段，提交到微信小程序的支付接口中即可

**Comment by superborges** [comment]
嗯，已经调试通过。多谢。
