### ISSUE TITLE
wx_pub_qr这个不能使用

### ISSUE THREAD

**Issue by menghuanwd** [PingPlusPlus/pingpp-js#18]
wx_pub_qr这个不能使用，我怎么调用微信扫码支付

**Comment by Hansongsong** [comment]
https://www.pingxx.com/docs/overview/flow/qr 看文档呀 大兄弟~微信扫描不需要客户端 SDK 的。

**Comment by menghuanwd** [comment]
那ping加加里的订单是怎么出现的，，如果不走客户端sdk，那就是直接走微信原来的sdk了？

**Comment by dong11** [comment]
返回的charge里有wx_pub_qr 链接  把这个转成二维码就行
