### ISSUE TITLE
怎么集成？

### ISSUE THREAD

**Issue by Liqiankun** [PingPlusPlus/pingpp-js#22]
我刚开始弄这个东西，我们用React做，文档不是很详细，完全不知道怎么开始啊！

**Comment by dong11** [comment]
@Liqiankun 导入dist目录下的pingpp.js就行   看文档 使用说明这个块 https://github.com/PingPlusPlus/pingpp-js/blob/master/README.md#使用说明

**Comment by Liqiankun** [comment]
@dong11 谢谢回复，已经有眉目了！

**Comment by Liqiankun** [comment]
@dong11 我用的是打包方式引用的js就是npm install pingpp-js 然后调用pingpp.createPayment(charge, function(result, err){})方法出现channel module "alipay" is undefined错误？请问是什么原因。

**Comment by dong11** [comment]
@Liqiankun H5不支持alipay  看一下https://www.pingxx.com/docs/client/sdk/web里面有支持的渠道

**Comment by Liqiankun** [comment]
@dong11 我的集成Ping++SDK的步骤是没问题的是吧？

**Comment by dong11** [comment]
@Liqiankun 恩  有错误说明流程是可以

**Comment by Liqiankun** [comment]
@dong11 成功出现支付页面！谢谢你的耐心回复。
