### ISSUE TITLE
v2.1.2微信内createPayment模拟付款后没有返回结果

### ISSUE THREAD

**Issue by librajt** [PingPlusPlus/pingpp-js#4]
页面加载时 偶尔有前端异常Can't find variable: _WXJS
iOS6.3.22稳定复现，Android正常、微信web开发者工具模拟正常

**Comment by li2go** [comment]
there is nobody wants to tell u how to deal with this question.

**Comment by samurai00** [comment]
#6 

已于 2.1.3 fixed

**Comment by wmlgl** [comment]
我在微信开发中也遇到了Can't find variable: _WXJS这个错误（没有使用这个js库），请问是怎样解决的？

**Comment by suibobuzhuliu** [comment]
@wmlgl 找到原因了么？
