### ISSUE TITLE
paypal 渠道 setUrlReturnCallback 无效

### ISSUE THREAD

**Issue by HDC-326** [PingPlusPlus/pingpp-js#42]
<pre>
// in channels/paypal.js
var utils = require('../utils');

module.exports = {
  handleCharge: function(charge) {
    var credential = charge.credential[charge.channel];
    utils.redirectTo(credential, ??);
  }
};
</pre>

**redirectTo 方法缺失 channel 参数**

**Comment by samurai00** [comment]
fixed on 3487787
