### ISSUE TITLE
支付宝小程序中使用了 window.location 报错 

### ISSUE THREAD

**Issue by HubertZhang** [PingPlusPlus/pingpp-js#49]
`src/collection.js:21` 使用了 window, 在支付宝小程序中调试时会出现如下报错

> Cannot read property 'location' of undefined

在[支付宝官方文档](https://docs.alipay.com/mini/framework/overview#%E9%80%BB%E8%BE%91%E7%BB%93%E6%9E%84) 中提到 window 在小程序中不可用

**Comment by samurai00** [comment]
2.2.15 已经修正
